[package]
name = "query-generator"
version = "0.1.0"
authors = ["smudgecat123 <jf14218@my.bristol.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
